// lib/constants.js

const MSG_TYPE = {
  NON_STREAM: 0,
  STREAM_START: 1,
  STREAM_DATA: 2,
  STREAM_END: 3,
  STREAM_DATA_FIRST: 4,
  STREAM_DATA_MIDDLE: 5,
  STREAM_DATA_LAST: 6,
  STREAM_DATA_RETRY: 7,
  STREAM_DATA_FAILED: 8,
  // 新增消息类型
  LLM_REQUEST: 9,         // 客户端 -> 服务器：LLM 对话请求
  LLM_RESPONSE: 10,       // 服务器 -> 客户端：LLM 响应
  IDENTIFY_SILLYTAVERN: 11, // SillyTavern -> 服务器: 身份标识
};

const STREAM_EVENTS = {
  START: 'CLIENT_STREAM_START', // 客户端 -> 服务器
  DATA_FIRST: 'CLIENT_STREAM_DATA_FIRST',
  DATA_MIDDLE: 'CLIENT_STREAM_DATA_MIDDLE',
  DATA_LAST: 'CLIENT_STREAM_DATA_LAST',
  DATA_RETRY: 'CLIENT_STREAM_DATA_RETRY',
  DATA_FAILED: 'CLIENT_STREAM_DATA_FAILED',
  END: 'CLIENT_STREAM_END',

  // 服务器 -> 客户端 (添加 _RESPONSE 后缀)
  START_RESPONSE: 'STREAM_START_RESPONSE',
  DATA_FIRST_RESPONSE: 'STREAM_DATA_FIRST_RESPONSE',
  DATA_MIDDLE_RESPONSE: 'STREAM_DATA_MIDDLE_RESPONSE',
  DATA_LAST_RESPONSE: 'STREAM_DATA_LAST_RESPONSE',
  DATA_RETRY_RESPONSE: 'STREAM_DATA_RETRY_RESPONSE',
  DATA_FAILED_RESPONSE: 'STREAM_DATA_FAILED_RESPONSE',
  END_RESPONSE: 'STREAM_END_RESPONSE',
};

const NAMESPACES = {
  GENERAL: '/',
  FUNCTION_CALL: '/function_call',
  EXTERNAL: '/external',
};

export { MSG_TYPE, STREAM_EVENTS, NAMESPACES };